#!/usr/bin/env bash
# ============================================
# VIDEO ↔ RUNTIME 部署桥接
# ============================================
# 用法（在 VIDEO 目录或任意目录）:
#   bash VIDEO/scripts/ensure_runtime_cpp.sh          # 编译 RUNTIME 并写 compose 挂载
#   bash VIDEO/scripts/ensure_runtime_cpp.sh wire     # 仅根据 deploy.env 写挂载（不重编译）
#   bash VIDEO/scripts/ensure_runtime_cpp.sh skip-check
#
# 依赖环境变量（可由调用方设置）:
#   EASYAIOT_ROOT          仓库根（默认由本脚本推断）
#   EASYAIOT_RUNTIME_SKIP=1
#   EASYAIOT_RUNTIME_REQUIRED=1
# ============================================
set -euo pipefail

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VIDEO_DIR="$(cd "$SCRIPT_PATH/.." && pwd)"
EASYAIOT_ROOT="${EASYAIOT_ROOT:-$(cd "$VIDEO_DIR/.." && pwd)}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Portable KEY=VALUE updater for .env.docker (reuse deploy_profile if available)
_set_env_docker_kv_local() {
  local file="$1" key="$2" value="$3"
  if type _set_env_docker_kv >/dev/null 2>&1; then
    _set_env_docker_kv "$file" "$key" "$value"
    return 0
  fi
  mkdir -p "$(dirname "$file")"
  touch "$file"
  if grep -qE "^${key}=" "$file" 2>/dev/null; then
    # portable in-place replace
    local tmp
    tmp="$(mktemp)"
    awk -v k="$key" -v v="$value" 'BEGIN{FS=OFS="="} $1==k{$0=k"="v} {print}' "$file" > "$tmp"
    mv "$tmp" "$file"
  else
    printf '%s=%s\n' "$key" "$value" >> "$file"
  fi
}

wire_runtime_override() {
  local deploy_env="${EASYAIOT_ROOT}/RUNTIME/deploy.env"
  local override_file="${VIDEO_DIR}/.docker-compose.runtime.override.yaml"
  local env_file="${VIDEO_DIR}/.env.docker"

  if [[ ! -f "$deploy_env" ]]; then
    print_warning "未找到 $deploy_env，跳过 RUNTIME 容器挂载"
    return 0
  fi

  set -a
  # shellcheck disable=SC1090
  source "$deploy_env"
  set +a

  if [[ ! -x "${RUNTIME_BIN:-}" ]]; then
    print_warning "RUNTIME 二进制不可执行: ${RUNTIME_BIN:-}"
    return 0
  fi

  if [[ ! -f "$env_file" ]]; then
    if [[ -f "${VIDEO_DIR}/env.example" ]]; then
      cp "${VIDEO_DIR}/env.example" "$env_file"
    else
      touch "$env_file"
    fi
  fi

  # Only mount a CUDA toolkit dir that contains libcudart.
  # Never mount generic system lib dirs (e.g. /usr/lib/x86_64-linux-gnu) —
  # they contain libc and break the container entrypoint.
  local cuda_host="" cuda_volume_line=""
  if [[ -n "${RUNTIME_CUDA_LIB_HOST:-}" ]]; then
    local cand
    IFS=':' read -r -a _cuda_cands <<< "${RUNTIME_CUDA_LIB_HOST}"
    for cand in "${_cuda_cands[@]}"; do
      [[ -d "$cand" ]] || continue
      case "$cand" in
        /usr/lib|/usr/lib/*|/lib|/lib/*|/usr/lib64|/lib64) continue ;;
      esac
      if compgen -G "${cand}/libcudart.so*" >/dev/null 2>&1; then
        cuda_host="$cand"
        break
      fi
    done
  fi

  local ld_path="/opt/easyaiot/runtime-conda-lib:/opt/easyaiot/ort-lib"
  if [[ -n "$cuda_host" ]]; then
    ld_path="${ld_path}:/opt/easyaiot/cuda-lib"
    cuda_volume_line="      - ${cuda_host}:/opt/easyaiot/cuda-lib:ro"
  fi

  _set_env_docker_kv_local "$env_file" RUNTIME_BIN "/opt/easyaiot/RUNTIME/build/RUNTIME"
  _set_env_docker_kv_local "$env_file" LD_LIBRARY_PATH "$ld_path"
  _set_env_docker_kv_local "$env_file" USE_GPU "${USE_GPU:-true}"
  _set_env_docker_kv_local "$env_file" RUNTIME_PREFER_GPU "${RUNTIME_PREFER_GPU:-true}"
  _set_env_docker_kv_local "$env_file" RUNTIME_HOST_DIR "${RUNTIME_HOST_DIR}"
  _set_env_docker_kv_local "$env_file" RUNTIME_CONDA_LIB_HOST "${RUNTIME_CONDA_LIB_HOST}"
  _set_env_docker_kv_local "$env_file" RUNTIME_ORT_LIB_HOST "${RUNTIME_ORT_LIB_HOST}"
  if [[ -n "$cuda_host" ]]; then
    _set_env_docker_kv_local "$env_file" RUNTIME_CUDA_LIB_HOST "$cuda_host"
  else
    # Clear stale unsafe value from earlier installs
    _set_env_docker_kv_local "$env_file" RUNTIME_CUDA_LIB_HOST ""
  fi

  {
    echo "# Auto-generated by VIDEO/scripts/ensure_runtime_cpp.sh — RUNTIME 高性能执行器挂载"
    echo "services:"
    echo "  video-service:"
    echo "    volumes:"
    echo "      - ${RUNTIME_HOST_DIR}:/opt/easyaiot/RUNTIME:ro"
    echo "      - ${RUNTIME_CONDA_LIB_HOST}:/opt/easyaiot/runtime-conda-lib:ro"
    echo "      - ${RUNTIME_ORT_LIB_HOST}:/opt/easyaiot/ort-lib:ro"
    if [[ -n "$cuda_volume_line" ]]; then
      echo "$cuda_volume_line"
    fi
    echo "    environment:"
    echo "      - RUNTIME_BIN=/opt/easyaiot/RUNTIME/build/RUNTIME"
    echo "      - LD_LIBRARY_PATH=${ld_path}"
    echo "      - USE_GPU=${USE_GPU:-true}"
    echo "      - RUNTIME_PREFER_GPU=${RUNTIME_PREFER_GPU:-true}"
  } > "$override_file"

  print_success "已配置 RUNTIME 容器挂载 ($override_file)"
}

ensure_runtime_cpp() {
  if [[ "$(uname -s)" != "Linux" ]]; then
    print_warning "当前系统 $(uname -s) 非 Linux：跳过 RUNTIME（C++/CUDA）一键编译。mac/Windows 请使用普通算法任务，或自行交叉编译。"
    return 0
  fi
  if [[ "${EASYAIOT_RUNTIME_SKIP:-0}" == "1" ]]; then
    print_warning "EASYAIOT_RUNTIME_SKIP=1，跳过 RUNTIME（高性能）编译"
    return 0
  fi

  local runtime_install="${EASYAIOT_ROOT}/RUNTIME/install_linux.sh"
  if [[ ! -f "$runtime_install" ]]; then
    print_warning "未找到 $runtime_install，跳过 RUNTIME 编译"
    return 0
  fi

  print_info "安装/编译 RUNTIME（算法任务高性能执行器，默认 GPU）..."
  if ! bash "$runtime_install" install; then
    print_warning "RUNTIME 编译失败：高性能任务将不可用，普通算法任务仍可使用"
    rm -f "${VIDEO_DIR}/.docker-compose.runtime.override.yaml"
    if [[ "${EASYAIOT_RUNTIME_REQUIRED:-0}" == "1" ]]; then
      print_error "EASYAIOT_RUNTIME_REQUIRED=1，终止"
      return 1
    fi
    return 0
  fi

  wire_runtime_override
}

main() {
  local cmd="${1:-install}"
  case "$cmd" in
    install|"")
      ensure_runtime_cpp
      ;;
    wire)
      wire_runtime_override
      ;;
    help|-h|--help)
      sed -n '2,18p' "$0"
      ;;
    *)
      print_error "未知命令: $cmd"
      exit 1
      ;;
  esac
}

main "$@"
